export const experiments = [
  {
    id: '01',
    title: 'The Adda Labs',
    status: 'active' as const,
    tags: ['venture lab', 'strategy'],
    teaser: 'A system for testing ideas before building them fully.',
    image: '/case-adda.png',
    why: 'I had many ideas and wanted to see them through to completion. The challenge was developing a clear structure for moving them forward.',
    what: 'Created a system to define goals clearly, test assumptions, and run small experiments to build momentum.',
    learned: 'Ideas started moving. Some reached their goal quickly. Others are still being developed. It became the base for everything I build now.',
    year: '2024',
    href: 'https://www.theaddalabs.com/',
  },
  {
    id: '02',
    title: 'TAL VI',
    status: 'exploring' as const,
    tags: ['revenue', 'execution'],
    teaser: 'The revenue layer of The Adda Labs.',
    image: '/case-talvi.png',
    why: 'TAL was helping me refine ideas. I also wanted to ensure the most valuable ones could sustain themselves.',
    what: 'Structured a separate layer focused on execution, value creation, and real-world outcomes from validated ideas.',
    learned: 'Used to verify whether ideas can create value and interest. Still early, still evolving.',
    year: '2025',
    href: 'https://tal-vi.vercel.app/',
  },
  {
    id: '03',
    title: 'Shutterphrase',
    status: 'exploring' as const,
    tags: ['advisory', 'branding'],
    teaser: 'Early advisory support for a production company started by a friend.',
    image: '/case-shutter.png',
    why: 'A friend started a production company and needed help shaping how it presented itself early on.',
    what: 'Helped shape their positioning, guided the website direction, and suggested ways to use tech to improve how the business runs.',
    learned: 'Brought more structure and clarity to how the business presents itself and operates.',
    year: '2025',
    href: 'https://www.shutterphrase.in/',
  },
  {
    id: '04',
    title: 'TPC Pharma',
    status: 'shipped' as const,
    tags: ['web design', 'client work'],
    teaser: 'Website for a pharma export company.',
    image: '/case-tpc.png',
    why: 'A client needed a clear, professional website that communicated their offerings to international buyers.',
    what: 'Designed and built their website with a focus on clarity and export positioning.',
    learned: 'Live and being used by the company.',
    year: '2024',
    href: 'https://tpc-website-jy4j.vercel.app/',
  },
  {
    id: '05',
    title: 'BTF Divyang Center',
    status: 'shipped' as const,
    tags: ['web design', 'accessibility'],
    teaser: 'Website for a special education center.',
    why: 'They needed a simple, clear online presence that worked well for parents and visitors.',
    what: 'Designed an accessible website focused on clear communication. Kept it simple on purpose.',
    learned: 'Live and useful for their audience.',
    year: '2024',
    href: 'https://btf-divyang-center.vercel.app/',
  },
]

export const thinking = [
  {
    id: '01',
    title: 'I focused on action over planning',
    excerpt: "I used to create many plans. To-do lists, notes, and ideas in my head. I wanted to see more results.",
    date: 'Mar 2026',
    readTime: '2 min',
    paragraphs: [
      "I used to create many plans.",
      "To-do lists, notes, and ideas in my head. I wanted to see more results.",
      "Most days ended with a desire for more progress.",
      "I had plenty of energy. I just needed a clear structure.",
      "So I made a simple weekly orientation guide.",
      "Something useful: what I aim to do, when I'll do it, and a way to observe my progress.",
      "First few days were a period of adjustment. Then something changed.",
      "I could see where I was hesitant. I could see where I was actually moving.",
      "That alone improved my focus.",
      "I started completing things. Small things, with consistency.",
      "It helped with focus, creative flow, and any feeling of hesitation.",
      "I became more intentional. I began being more honest about my process.",
    ],
    takeaway: "Clarity beats motivation. If you can see your week clearly, you'll act better.",
    href: '#',
  },
  {
    id: '02',
    title: 'I had too many ideas. So I built a system for them.',
    excerpt: "I've always had ideas. Most of them stayed in my head. Nothing really got built.",
    date: 'Feb 2026',
    readTime: '2 min',
    paragraphs: [
      "I've always had ideas.",
      "Creative ones. Business ideas. Product ideas. Most stayed in my head for a while.",
      "I would think about them, maybe talk about them, and then move on to the next one.",
      "I wanted to see them become real.",
      "The goal was to add more structure.",
      "So I decided to treat ideas with more intention.",
      "That's how The Adda Labs started.",
      "Not as a startup. More like a system.",
      "A way to take ideas out of my head, test them in the real world, and see what actually works.",
      "I also started bringing in people. Different skills. Different perspectives.",
      "Now ideas have a clear path. They get worked on.",
      "Some find their place quickly. Some move forward.",
      "Everything is more tangible now. More action. More progress.",
    ],
    takeaway: "Execution brings ideas to life. Every idea finds its value through action.",
    href: '#',
  },
  {
    id: '03',
    title: 'I began as I was',
    excerpt: "For a long time, I thought I should be ready before starting. I decided to dive in.",
    date: 'Jan 2026',
    readTime: '2 min',
    paragraphs: [
      "For a long time, I thought I should be ready before starting anything.",
      "Ready with skills. Ready with clarity. Ready with a detailed plan.",
      "I spent a lot of time preparing.",
      "I would research more. View more guides. Think more.",
      "It was a learning phase. And then I decided to take action.",
      "Then I noticed something.",
      "Every time I actually started something, I learned exactly what was needed while doing it.",
      "Action brought clarity.",
      "The first version was an initial step. And it existed.",
      "And once something exists, you can refine it.",
      "That's how most of my work was successfully built.",
      "I started and learned along the way.",
      "Now I find clarity through action.",
      "I start small. Then adjust as I go.",
      "It is a living process. Things move.",
    ],
    takeaway: "Clarity comes from action. You find your way by moving forward.",
    href: '#',
  },
]
