export const experiments = [
  {
    id: '01',
    title: 'The Adda Labs',
    status: 'active' as const,
    tags: ['venture lab', 'strategy'],
    teaser: 'Where I test ideas before they become real products.',
    image: '/case-adda.png',
    why: 'I had too many ideas and not enough follow-through. I needed a way to get them out of my head and into the world.',
    what: 'I built a system to define goals, test my assumptions, and run small experiments to build some momentum.',
    learned: "Things finally started moving. Some ideas worked, some didn't, but they all became the baseline for everything I build now.",
    year: '2024',
    href: 'https://www.theaddalabs.com/',
  },
  {
    id: '02',
    title: 'TAL VI',
    status: 'exploring' as const,
    tags: ['revenue', 'execution'],
    teaser: 'How Adda Labs pays for itself.',
    image: '/case-talvi.png',
    why: 'Adda Labs was great for refining ideas, but I wanted to make sure the best ones could actually sustain themselves.',
    what: 'I built a layer focused entirely on execution, value creation, and making sure validated ideas turned into real outcomes.',
    learned: "It's how I check if an idea actually has legs. It's still early, but it's evolving every day.",
    year: '2025',
    href: 'https://tal-vi.vercel.app/',
  },
  {
    id: '03',
    title: 'Shutterphrase',
    status: 'exploring' as const,
    tags: ['advisory', 'branding'],
    teaser: "Helping a friend's production company find its voice.",
    image: '/case-shutter.png',
    why: 'A friend started a production company and needed a hand figuring out how to present themselves to the world.',
    what: 'I helped shape their positioning, guided the website, and found ways to use tech to make the business run smoother.',
    learned: 'It brought a lot of clarity to how they present themselves and how they work day-to-day.',
    year: '2025',
    href: 'https://www.shutterphrase.in/',
  },
  {
    id: '04',
    title: 'TPC Pharma',
    status: 'shipped' as const,
    tags: ['web design', 'client work'],
    teaser: 'A clean, professional home for a pharma export business.',
    image: '/case-tpc.png',
    why: 'The client needed a site that looked professional enough to talk to international buyers without the fluff.',
    what: 'I designed and built the site with focus on clarity and getting straight to the point.',
    learned: "It's live, working, and doing exactly what it was meant to do.",
    year: '2024',
    href: 'https://tpc-website-jy4j.vercel.app/',
  },
]

export const thinking = [
  {
    id: '01',
    title: 'Doing more, planning less',
    excerpt: "I used to spend all my time making lists and taking notes. I had the energy, I just didn't have the results.",
    date: 'Mar 2026',
    readTime: '2 min',
    paragraphs: [
      "I used to create a lot of plans.",
      "To-do lists, notes, and hundreds of ideas floating in my head. I wanted to see more results.",
      "Most days ended with me wishing I'd made more progress.",
      "I had plenty of energy, I just needed a clear way to use it.",
      "So I made a simple weekly orientation guide.",
      "Just the basics: what I want to do, when I'll do it, and a way to track if I'm actually doing it.",
      "The first few days were weird. Then something clicked.",
      "I could see where I was hesitating and where I was actually moving.",
      "That alone changed my focus.",
      "I started finishing things. Small things, but with consistency.",
      "It helped with my creative flow and killed that feeling of hesitation.",
      "I'm more intentional now, and a lot more honest about my own process.",
    ],
    takeaway: "Clarity beats motivation every time. If you can see your week clearly, you'll act better.",
    href: '#',
  },
  {
    id: '02',
    title: 'Building a home for my ideas',
    excerpt: "I've always had ideas, but most of them stayed in my head. I wanted them to be real.",
    date: 'Feb 2026',
    readTime: '2 min',
    paragraphs: [
      "I've always had ideas.",
      "Creative ones, business ones, product ones. Most of them stayed in my head for way too long.",
      "I'd think about them, talk about them, and then move on to the next thing.",
      "I wanted to see them actually exist.",
      "I needed more structure, so I decided to treat my ideas with more respect.",
      "That's how The Adda Labs started.",
      "It's not a startup, it's more like a system.",
      "A way to take ideas out of my head, test them in the real world, and see what actually works.",
      "I also started bringing in other people with different skills and perspectives.",
      "Now, my ideas have a clear path. They get worked on.",
      "Some find their place quickly, some take longer to move forward.",
      "Everything feels more tangible. There's more action and a lot more progress.",
    ],
    takeaway: "Execution is what brings ideas to life. Every idea finds its value through action.",
    href: '#',
  },
  {
    id: '03',
    title: 'Starting as I am',
    excerpt: "I thought I had to be 'ready' before I could start. I was wrong.",
    date: 'Jan 2026',
    readTime: '2 min',
    paragraphs: [
      "For a long time, I thought I should be ready before starting anything.",
      "Ready with the right skills, ready with total clarity, and ready with a perfect plan.",
      "I spent a lot of time preparing.",
      "I'd research, read guides, and overthink everything.",
      "It was a learning phase, but I wasn't actually doing anything.",
      "Then I noticed something.",
      "Every time I actually started, I learned exactly what was needed while I was doing it.",
      "Action brought the clarity I was looking for in my research.",
      "The first version was just a step, but it existed.",
      "And once something exists, you can make it better.",
      "That's how most of my work actually got built.",
      "I started and learned along the way.",
      "Now I find clarity through action, not before it.",
      "I start small, then adjust. It's a living process, and things are moving.",
    ],
    takeaway: "Clarity comes from moving. You find your way by going forward.",
    href: '#',
  },
]
